#!/bin/bash
# THIS FILE: build_for_each_project
# PS: Do not save this file into git

   Ctitle="\033[1;38;5;15;1;48;5;30m"
    Citem="\033[1;38;5;36m"
     Coff="\033[m"
    Cname="\033[40m\033[0;33m"
  DOCKDIR=$(dirname "$(readlink -f ${BASH_SOURCE[0]})")
DOCKBUILD=$(basename $DOCKDIR)
 DOCKREPO=$(basename $(dirname $DOCKDIR))
  DOCKTAG=${1:-"latest"}
 DOCKNAME=${2:-${PWD##*/}}
   TMPPWD=$(pwd)
   indent="    "

cd $DOCKDIR
echo -e "\n  ${Cname} ${DOCKNAME} >> ${Ctitle}  Preparing files :  ${Coff}${Citem}\n"

folders="*.sh pre-init.d/ install.d/"

if [ -d "profile.d" ]; then
  folders="${folders} profile.d/"
fi

tar -cvf files.tar  $folders | sed "s/^/${indent}↠ /"

echo -e "\n  ${Cname} ${DOCKNAME} >> ${Ctitle}  Proceed Dockerfile build : ${Coff}\n
"

docker build --force-rm -t ${DOCKREPO}/${DOCKBUILD}:${DOCKTAG} . | sed "s/^/${indent}/"
cd $TMPPWD
