#!/bin/bash
# @app      docker-images
# @author   cahato https://github.com/c4tom

tag=${1:-"latest"}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TAG=${1:-''}
for project in `ls -d */`; do
    cd "$DIR/$project"
    
    ./build "$tag"
done
