#!/bin/bash
# @app      docker-images
# @author   cahato https://github.com/c4tom

tag=${1:-"latest"}
DIR=${PWD##*/}
IMGMD=../images.md

echo "# Available Images

| Imagem | Tamanho|
|-|-|" > $IMGMD

for project in $(find ./ -name Dockerfile); do
    image=$(echo $project | sed "s#\./##" | sed "s#/Dockerfile##")
    SIZE=$(docker inspect --format='{{.Size}}' $DIR/$image:$tag | awk '{printf "%.2f MB\n", $1/1000000}')
    echo "|$image|~ $SIZE|" >> $IMGMD
    docker images $DIR/$image:$tag
done
